version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Qatar
    open-pull-requests-limit: 5
    labels: [dependencies, python]
    commit-message:
      prefix: deps(py)
      include: scope

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Qatar
    open-pull-requests-limit: 5
    labels: [dependencies, npm]
    commit-message:
      prefix: deps(js)
      include: scope
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Qatar
    labels: [dependencies, github-actions]
    commit-message:
      prefix: ci(deps)
      include: scope
